version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - ~/data/mongodb2:/data/db
    ports:
      - 27017:27017
    networks:
      - local

  paras-app:
    build: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - local

networks:
  local:
    driver: bridge